[package]
name = "agon-light-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
agon-cpu-emulator = { path="./agon-cpu-emulator"}
agon-light-vdp = { path="./agon-light-vdp"}

